export const STRIPE_PUBLISHABLE_KEY = "pk_live_h0dVPsHjrvKM0AXQFEuWEX3J"
export const SUPABASE_URL = "https://aynyvirtzioyeshauith.supabase.co"
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bnl2aXJ0emlveWVzaGF1aXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NjEzODcsImV4cCI6MjA5MzMzNzM4N30.q1hfzEtVylk2_1a3hdc1gRZ9jZNLB4YKdK77A9mqHBM"
